import "src/styles/globals.css";
import type { AppProps } from "next/app";
import { MantineProvider } from "@mantine/core";
import Head from "next/head";
import { useEffect } from "react";
import useGlobalViewModel, { GlobalContext } from "@/lib/firebase/firebase";

export default function App({ Component, pageProps }: AppProps) {
  const globalViewModel = useGlobalViewModel();

  return (
    <GlobalContext.Provider value={{ ...globalViewModel }}>
      <MantineProvider
        withGlobalStyles
        withNormalizeCSS
        theme={{
          colorScheme: "light",
        }}
      >
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Component {...pageProps} />
      </MantineProvider>
    </GlobalContext.Provider>
  );
}
