import { MainLayout } from "@/src/components/Layout/mainlayout";
import { Index } from "@/src/components/pages";
import { About } from "@/src/components/pages/about";
import Head from "next/head";

const Home = () => {
  return (
    <MainLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <About />
    </MainLayout>
  );
};

export default Home;
